name             'mysql-cluster'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures mysql-cluster'
long_description 'Installs/Configures mysql-cluster'
version          '0.1.0'

depends 'apt'
depends 'percona'
