name             'mysql-cluster'
maintainer       'Adam Krone'
maintainer_email 'adam.krone@thirdwavellc.com'
license          'Apache v2.0'
description      'Installs/Configures mysql-cluster'
long_description 'Installs/Configures mysql-cluster'
version          '0.2.0'

depends 'apt'
depends 'percona'
